### ISSUE TITLE
save_input() returns no errors. 

### ISSUE THREAD

**Issue by joselara** [ShawnMcCool/laravel-form-base-model#8]
So when I use:          

return Redirect::back()->with_input()->with_errors( PropertyForm::$validation );
I get no rule errors, but redirects with input

But

PropertyForm::save_input();
return Redirect::back()->with_errors( PropertyForm::$validation );

returns rule errors

Is this the way form-base-model is supposed to be used without with_input?

Thx for this great bundle.

**Comment by ShawnMcCool** [comment]
I'm trying to understand you as completely as possible. Could you give me example code and more information?

**Comment by joselara** [comment]
```
    if( PropertyForm::is_valid() )
    {


        $p = new Home;


        $p->property_streetnum = PropertyForm::get('property_streetnum');
        $p->property_streetname = PropertyForm::get('property_streetname');
        $p->save();

        return Redirect::to_route('property.details', array($p->property_id));
    }
    else{

        return Redirect::back()->with_input()->with_errors( PropertyForm::$validation );

    }
```

**Comment by ShawnMcCool** [comment]
Thank you, and what methods are you using on the form to display the errors? I ask to set up an equivalent testing setup on my side.

**Comment by joselara** [comment]
``` php
@if($errors->has())

    @foreach ($errors->all() as $error)
       {{ $error }}
    @endforeach

@endif
```

**Comment by ShawnMcCool** [comment]
Thank you, I'll follow up within the next day or so.

**Comment by joselara** [comment]
Shawn, I was running 1.3, just updated to 1.4 and the issue is gone. 
Sorry to bother you.

**Comment by ShawnMcCool** [comment]
No problem, glad it worked out.
